apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby
  labels:
    app: dobby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dobby
  template:
    metadata:
      labels:
        app: dobby
    spec:
      containers:
        - name: dobby
          image: thecasualcoder/dobby
          env:
            - name: VERSION
              value: "2.0"
            - name: INITIAL_DELAY
              value: "0"
            - name: INITIAL_HEALTH
              value: "TRUE"
            - name: INITIAL_READINESS
              value: "TRUE"
          ports:
            - containerPort: 4444
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4444
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 4444
            initialDelaySeconds: 20
            periodSeconds: 3
